fix build error on loongarch64
cpu/cpu_loong64.go:10:7: CacheLineSize redeclared in this block
	cpu/cpu.go:20:5: other declaration of CacheLineSize
cpu/cpu.go:15:30: undefined array length CacheLinePadSize or missing type constraint
cpu/cpu.go:20:29: undefined: CacheLinePadSize
cpu/cpu.go:123:2: undefined: doinit